corrected typo

diff --git a/.github/workflows/autoflake_format.yml b/.github/workflows/autoflake_format.yml
--- a/.github/workflows/autoflake_format.yml
+++ b/.github/workflows/autoflake_format.yml
@@ -7,7 +7,7 @@ on:
   workflow_dispatch:
 
 jobs:
-  black-check:
+  autoflake-check:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
@@ -27,4 +27,6 @@ jobs:
 
       - name: Check Autoflake Output
         if: steps.autoflake.outcome == 'failure'
-        run: echo "Autoflake check failed. To fix, please run `poetry run autoflake .`"
+        run: |
+          echo "Autoflake check failed. To fix, please run 'poetry run autoflake .'"
+          exit 1
diff --git a/.github/workflows/black_format.yml b/.github/workflows/black_format.yml
--- a/.github/workflows/black_format.yml
+++ b/.github/workflows/black_format.yml
@@ -27,7 +27,11 @@ jobs:
 
       - name: Check Black Output
         if: steps.black.outcome == 'failure'
-        run: echo "Black check failed. To fix, please run `poetry run black .`"
+        run: |
+          echo "Black check failed. To fix, please run 'poetry run black .'"
+          exit 1
+
+
 
       # (Optional) If you want to automatically fix formatting issues
       # Uncomment the following steps:
diff --git a/.github/workflows/isort_format.yml b/.github/workflows/isort_format.yml
--- a/.github/workflows/isort_format.yml
+++ b/.github/workflows/isort_format.yml
@@ -7,7 +7,7 @@ on:
   workflow_dispatch:
 
 jobs:
-  black-check:
+  isort-check:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
@@ -27,4 +27,6 @@ jobs:
 
       - name: Check isort Output
         if: steps.isort.outcome == 'failure'
-        run: echo "isort check failed. To fix, please run `poetry run isort .`"
+        run: |
+          echo "isort check failed. To fix, please run 'poetry run isort .'"
+          exit 1
